In [1]:
import pandas as pd

In [7]:
med = pd.read_csv('privatized-mediocre-quality.csv')

In [8]:
med

,epsilon,neighborhood,year,month,0,1,2,3,4,5,...,164,165,166,167,168,169,170,171,172,173
0,4.0,0,2019,1,0,12,3,1,0,0,...,0,6,0,0,0,1,2,0,0,0
1,4.0,0,2019,2,2,0,2,0,10,0,...,1,0,1,0,0,0,0,1,2,0
2,4.0,0,2019,3,0,1,0,6,2,0,...,15,7,0,0,0,5,18,0,2,0
3,4.0,0,2019,4,14,6,6,0,0,0,...,3,0,6,0,0,0,0,0,0,1
4,4.0,0,2019,5,0,1,0,0,0,0,...,6,0,1,0,0,1,0,0,7,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3331,4.0,277,2019,8,3,0,8,12,0,4,...,13,1,0,3,9,0,7,0,2,0
3332,4.0,277,2019,9,0,0,0,5,0,1,...,2,2,0,0,0,3,4,15,0,0
3333,4.0,277,2019,10,0,0,0,0,0,1,...,0,0,5,5,0,0,6,2,0,3
3334,4.0,277,2019,11,2,0,0,0,3,0,...,1,0,2,0,0,4,0,2,0,14
3335,4.0,277,2019,12,0,0,1,0,0,0,...,0,30,9,0,5,13,5,3,0,0